##
#
# Travis CI script for keyvi
#


language: cpp

compiler:
# disable, does not build with current msgpack - clang
  - gcc

python:
  - 2.7

sudo: required

services:
  - docker

env:
  matrix:
    - BUILD_TYPE=linux      PYTHON_VERSION=27     CONF=debug      ARCH=x86_64
    - BUILD_TYPE=linux      PYTHON_VERSION=34     CONF=debug      ARCH=x86_64
    - BUILD_TYPE=linux      PYTHON_VERSION=35     CONF=debug      ARCH=x86_64
    - BUILD_TYPE=linux      PYTHON_VERSION=pypy2  CONF=debug      ARCH=x86_64
    - BUILD_TYPE=linux      PYTHON_VERSION=27     CONF=release    ARCH=x86_64
    - BUILD_TYPE=linux      PYTHON_VERSION=34     CONF=release    ARCH=x86_64
    - BUILD_TYPE=linux      PYTHON_VERSION=35     CONF=release    ARCH=x86_64
    - BUILD_TYPE=linux      PYTHON_VERSION=pypy2  CONF=release    ARCH=x86_64
    - BUILD_TYPE=linux      PYTHON_VERSION=27     CONF=coverage   ARCH=x86_64
    - BUILD_TYPE=manylinux  PYTHON_VERSION=27     DOCKER_IMAGE=keyvidev/keyvi-manylinux-builder
    - BUILD_TYPE=manylinux  PYTHON_VERSION=34     DOCKER_IMAGE=keyvidev/keyvi-manylinux-builder
    - BUILD_TYPE=manylinux  PYTHON_VERSION=35     DOCKER_IMAGE=keyvidev/keyvi-manylinux-builder
    - BUILD_TYPE=sdist      PYTHON_VERSION=27
    - BUILD_TYPE=doc
    - BUILD_TYPE=rust

  global:
    - GH_REPO_NAME='keyvi'
    - DOXYFILE="$TRAVIS_BUILD_DIR/keyvi/keyvi.Doxyfile"
    - GITHUB_REPO='KeyviDev/keyvi'
    - GH_REPO_REF='github.com/KeyviDev/keyvi.git'

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: BUILD_TYPE=osx PYTHON_VERSION=27
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: BUILD_TYPE=osx PYTHON_VERSION=34
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: BUILD_TYPE=osx PYTHON_VERSION=35
# temporarily disabled pypy builds on osx
# till https://bitbucket.org/pypy/pypy/issues/2626/invalid-conversion-from-const-char-to-char is released
#    - os: osx
#      osx_image: xcode7.3
#      compiler: clang
#      env: BUILD_TYPE=osx PYTHON_VERSION=pypy2

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./travis/setup_osx.sh ; fi
  - if [ "PYTHON_VERSION" != "" ]; then source ./travis/setup_pyenv.sh ; fi
  - if [ "$BUILD_TYPE" == "rust" ]; then ./travis/setup_rust.sh ; fi

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$DOCKER_IMAGE" != "" ]; then docker pull $DOCKER_IMAGE ; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
# disable, LLVM broken for now    - llvm-toolchain-precise-3.6
    - boost-latest
    packages:
    - gcc-4.8
    - g++-4.8
# disabled due to https://github.com/travis-ci/travis-ci/issues/6120    - clang
    - valgrind
    - cmake
    - libboost-thread1.55-dev
    - libboost-system1.55-dev
    - libboost-test1.55-dev
    - libboost1.55-dev
    - libboost-date-time1.55-dev
    - libboost-regex1.55-dev
    - libboost-filesystem1.55-dev
    - libboost-program-options1.55-dev
    - libboost-iostreams1.55-dev
    - libsnappy-dev
    - zlib1g-dev
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz
    - libstdc++-4.8-dev
    - clang-format-3.8

script:
  - if [ "$BUILD_TYPE" == "linux" ]; then source ./travis/build_linux.sh ; fi
  - if [ "$BUILD_TYPE" == "manylinux" ]; then source ./travis/build_manylinux_package.sh ; fi
  - if [ "$BUILD_TYPE" == "sdist" ]; then source ./travis/build_sdist_package.sh ; fi
  - if [ "$BUILD_TYPE" == "osx" ]; then source ./travis/build_osx_package.sh ; fi
  - if [ "$BUILD_TYPE" == "rust" ]; then source ./travis/build_rust.sh ; fi

after_success:
  - if [ "$CC" = "gcc-4.8" ] && [ "$CONF" = "coverage" ]; then ./travis/coverage.sh ; fi
  - if [ "$CC" = "gcc-4.8" ] && [ "$CONF" = "coverage" ]; then ./travis/style.sh ; fi
  - if [ "$BUILD_TYPE" == "doc" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then source ./travis/build_doc.sh ; fi

deploy:
  provider: script
  script: travis/upload_packages.sh
  skip_cleanup: true
  on:
    tags: true
