##
#
# Travis CI script for keyvi
#


language: cpp

compiler:
# disable, does not build with current msgpack - clang
  - gcc

python:
  - 2.7

cache:
  directories:
    - $HOME/.pip-cache

env:
  matrix:
    - CONF=debug   ARCH=x86_64
    - CONF=release ARCH=x86_64
    - CONF=coverage ARCH=x86_64
  global:
    - GITHUB_REPO='cliqz-oss/keyvi'
    - secure: "cy3LYIeuSxIdDt4GArpStoawmlEXy7oVX/Z72hwcXVj6EgQ8za16GaayQCLbHy9Hlm0K42QmWg4s7iOm/QzKBlZAwvHMktmHIVoovXe+i83bRVclMr/zvzhEeSyCy4xbBEBT8qt4p0dwX4hOF6cfy+rpNsI+CMBbGgMSS/MZHm/FmF5fKqcZBJfZfEPOqOukID4NPirDlZ8Jmg8JR1K722+xXvwbSif0a6wJ3p517JjYJxO8a7AzdXJMXC3sJmpsSCBwp+NG9BrwJ/MgQFHKUEhPoPFOEI7P57rH9Cax8+y9j7ukwlB36Ae5ApddcXYbQMOtpoA+DvR5JbsbYWi4/T6qUntYmpRy5gPVD/IwIAldEt3iERswjWFHgUjN+JaJ6YqQHl5ks++NZbB6W8eqP2Id1Oa669b6uxFn62Ln43TcvY4bapJEscj7goReiQGjwIWjBxphP/eJaPae642HnpBijPjAG+uA8IyO2nuY/+xULMiNXDFGVmBC5VfYp95Y71ZlUpfUv6u96mXc3ruWmDRzGNNgNXmzIGfD5bxn2uxMykOW6ubG4mnxOT/qMia8yrYsPYdBsvc1u2XWHAUUrHPVr9HmFo68y3AfuXwXH2Eb0fGTxNmaihabcqoBdm6HRK3aRLqXweBI2xXyOY8Tf07hUy+G7qkg2ZrsEgwWg+k="  # COVERALLS_REPO_TOKEN

before_install:
  - pip install --user --download-cache $HOME/.pip-cache --use-wheel --install-option="--no-cython-compile" cython
  - pip install --user --download-cache $HOME/.pip-cache --use-wheel pytest
  - if [ "$CC" = "gcc" ] && [ "$CONF" = "coverage" ]; then pip install --user --download-cache $HOME/.pip-cache --use-wheel cpp-coveralls; fi
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - boost-latest
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - scons
    - valgrind
    - cmake
    - clang
    - libboost-thread1.55-dev
    - libboost-system1.55-dev
    - libboost-test1.55-dev
    - libboost1.55-dev
    - libboost-date-time1.55-dev
    - libboost-regex1.55-dev
    - libboost-filesystem1.55-dev
    - libboost-program-options1.55-dev
    - libboost-iostreams1.55-dev
    - libsnappy-dev
    - zlib1g-dev
    - doxygen
    - libstdc++-4.8-dev

script:
  - cd keyvi
  - scons -j 4 mode=$CONF
  - $CONF/dictionaryfsa_unittests/dictionaryfsa_unittests
  - cd ../pykeyvi
  - python setup.py build
  - python setup.py install --user
  - py.test tests
  - cd ..

sudo: false
after_success:
  - if [ "$CC" = "gcc-4.8" ] && [ "$CONF" = "coverage" ]; then coveralls -r keyvi -b keyvi --gcov /usr/bin/gcov-4.8 --gcov-options '\-lp' -e 3rdparty --repo-token "${COVERALLS_REPO_TOKEN}" ; fi
