##
#
# Travis CI script for keyvi
#

language: cpp

compiler:
  - gcc

python:
  - 3.6

sudo: required

services:
  - docker

env:
  matrix:
#    - BUILD_TYPE=linux      DOCKER_IMAGE=keyvidev/ubuntu-builder      CONF=release
#    - BUILD_TYPE=linux      DOCKER_IMAGE=keyvidev/ubuntu-builder      CONF=debug

#    - BUILD_TYPE=python     DOCKER_IMAGE=keyvidev/ubuntu-builder      PYTHON_VERSION=3.6.12         CONF=release
#    - BUILD_TYPE=python     DOCKER_IMAGE=keyvidev/ubuntu-builder      PYTHON_VERSION=3.7.9          CONF=release
#    - BUILD_TYPE=python     DOCKER_IMAGE=keyvidev/ubuntu-builder      PYTHON_VERSION=3.8.6          CONF=release
#    - BUILD_TYPE=python     DOCKER_IMAGE=keyvidev/ubuntu-builder      PYTHON_VERSION=3.9.0          CONF=release
#    - BUILD_TYPE=python     DOCKER_IMAGE=keyvidev/ubuntu-builder      PYTHON_VERSION=pypy3.6-7.2.0  CONF=release

#    - BUILD_TYPE=python     DOCKER_IMAGE=keyvidev/ubuntu-builder      PYTHON_VERSION=3.6.12         CONF=debug
#    - BUILD_TYPE=python     DOCKER_IMAGE=keyvidev/ubuntu-builder      PYTHON_VERSION=3.7.9          CONF=debug
#    - BUILD_TYPE=python     DOCKER_IMAGE=keyvidev/ubuntu-builder      PYTHON_VERSION=3.8.6          CONF=debug
#    - BUILD_TYPE=python     DOCKER_IMAGE=keyvidev/ubuntu-builder      PYTHON_VERSION=3.9.0          CONF=debug
#    - BUILD_TYPE=python     DOCKER_IMAGE=keyvidev/ubuntu-builder      PYTHON_VERSION=pypy3.6-7.2.0  CONF=debug

    - BUILD_TYPE=sdist      DOCKER_IMAGE=keyvidev/ubuntu-builder

#    - BUILD_TYPE=manylinux  DOCKER_IMAGE=keyvidev/manylinux-builder         PYTHON_PATH=cp36-cp36m
#    - BUILD_TYPE=manylinux  DOCKER_IMAGE=keyvidev/manylinux-builder         PYTHON_PATH=cp37-cp37m
#    - BUILD_TYPE=manylinux  DOCKER_IMAGE=keyvidev/manylinux-builder         PYTHON_PATH=cp38-cp38
#    - BUILD_TYPE=manylinux  DOCKER_IMAGE=keyvidev/manylinux-builder         PYTHON_PATH=cp39-cp39

#    - BUILD_TYPE=rust       DOCKER_IMAGE=keyvidev/ubuntu-builder

#    - BUILD_TYPE=coverage   DOCKER_IMAGE=keyvidev/ubuntu-builder:coverage.16.04

    - BUILD_TYPE=doc        DOCKER_IMAGE=keyvidev/ubuntu-builder

 #   - BUILD_TYPE=style      DOCKER_IMAGE=keyvidev/ubuntu-builder

  global:
    - GITHUB_REPO='KeyviDev/keyvi'

#matrix:
#  include:
#    - os: osx
#      osx_image: xcode9.4
#      compiler: clang
#      env: BUILD_TYPE=osx PYTHON_VERSION=3.6.12
#    - os: osx
#      osx_image: xcode9.4
#      compiler: clang
#      env: BUILD_TYPE=osx PYTHON_VERSION=3.7.9
#    - os: osx
#      osx_image: xcode9.4
#      compiler: clang
#      env: BUILD_TYPE=osx PYTHON_VERSION=3.8.6
#    - os: osx
#      osx_image: xcode9.4
#      compiler: clang
#      env: BUILD_TYPE=osx PYTHON_VERSION=3.9.0
#    - os: osx
#      osx_image: xcode9.4
#      compiler: clang
#      env: BUILD_TYPE=osx PYTHON_VERSION=pypy3.6-7.2.0

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then source ./travis/setup_osx.sh ; fi

install:
  - if [ "$DOCKER_IMAGE" != "" ]; then docker pull $DOCKER_IMAGE ; fi

script:
  - if [ "$BUILD_TYPE" == "linux" ]; then docker run --rm -v `pwd`:/io -e CONF $DOCKER_IMAGE  /io/travis/build_linux.sh ; fi

  - if [ "$BUILD_TYPE" == "python" ]; then
      docker run --rm -v `pwd`:/io -e CONF -e PYTHON_VERSION $DOCKER_IMAGE  /io/travis/build_python.sh ; fi

  - if [ "$BUILD_TYPE" == "manylinux" ]; then
      docker run --rm -v `pwd`:/io -e PYTHON_PATH $DOCKER_IMAGE  /io/travis/build_manylinux_wheels.sh ; fi

  - if [ "$BUILD_TYPE" == "sdist" ]; then
      docker run --rm -v `pwd`:/io -e PYTHON_VERSION $DOCKER_IMAGE  /io/travis/build_sdist_package.sh ; fi

  - if [ "$BUILD_TYPE" == "osx" ]; then source ./travis/build_osx_package.sh ; fi

  - if [ "$BUILD_TYPE" == "rust" ]; then docker run --rm -v `pwd`:/io $DOCKER_IMAGE  /io/travis/build_rust.sh ; fi

  - if [ "$BUILD_TYPE" == "coverage" ]; then
      docker run --rm -v `pwd`:/io -e TRAVIS -e TRAVIS_JOB_ID -e TRAVIS_BRANCH -e TRAVIS_PULL_REQUEST $DOCKER_IMAGE /io/travis/coverage.sh ; fi

  - if [ "$BUILD_TYPE" == "doc" ] && [ "$TRAVIS_REPO_SLUG" == "$GITHUB_REPO" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      source ./travis/build_doc.sh ; fi

  - if [ "$BUILD_TYPE" == "style" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      docker run --rm -v `pwd`:/io -e TRAVIS_COMMIT_RANGE $DOCKER_IMAGE /io/travis/style.sh ; fi

deploy:
  provider: script
  script: travis/upload_packages.sh
  skip_cleanup: true
  on:
    tags: true
