name: Pre-commit auto-update

on:
  # every monday at midnight
  schedule:
    - cron: "0 0 * * 1"
  # on demand
  workflow_dispatch:

jobs:
  upgrade:
    uses: browniebroke/github-actions/.github/workflows/pre-commit-autoupdate.yml@v1.23.0
    secrets:
      gh_pat: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
    with:
      # Inputs listed with their default (all optional)
      config_path: ".pre-commit-config.yaml" # path is relative to repository root
      python_version: "3.11"
      branch_name: "update/pre-commit-hooks"
      pull_request_title: "chore: upgrade pre-commit dependencies"
      commit_message: "chore: upgrade pre-commit dependencies"
